/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Manipulator } from './Manipulator';
import {
    ManipulatorFromJSON,
    ManipulatorFromJSONTyped,
    ManipulatorToJSON,
} from './Manipulator';

/**
 * 
 * @export
 * @interface DataManipulation
 */
export interface DataManipulation {
    /**
     * 
     * @type {Array<Manipulator>}
     * @memberof DataManipulation
     */
    manipulators: Array<Manipulator>;
}

/**
 * Check if a given object implements the DataManipulation interface.
 */
export function instanceOfDataManipulation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "manipulators" in value;

    return isInstance;
}

export function DataManipulationFromJSON(json: any): DataManipulation {
    return DataManipulationFromJSONTyped(json, false);
}

export function DataManipulationFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataManipulation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'manipulators': ((json['manipulators'] as Array<any>).map(ManipulatorFromJSON)),
    };
}

export function DataManipulationToJSON(value?: DataManipulation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'manipulators': ((value.manipulators as Array<any>).map(ManipulatorToJSON)),
    };
}

