/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditProjectDTO
 */
export interface EditProjectDTO {
    /**
     * 
     * @type {string}
     * @memberof EditProjectDTO
     */
    projectName: string;
}

/**
 * Check if a given object implements the EditProjectDTO interface.
 */
export function instanceOfEditProjectDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "projectName" in value;

    return isInstance;
}

export function EditProjectDTOFromJSON(json: any): EditProjectDTO {
    return EditProjectDTOFromJSONTyped(json, false);
}

export function EditProjectDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditProjectDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'projectName': json['projectName'],
    };
}

export function EditProjectDTOToJSON(value?: EditProjectDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'projectName': value.projectName,
    };
}

