/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EngineDeploymentDTO
 */
export interface EngineDeploymentDTO {
    /**
     * 
     * @type {string}
     * @memberof EngineDeploymentDTO
     */
    type: EngineDeploymentDTOTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof EngineDeploymentDTO
     */
    tier?: EngineDeploymentDTOTierEnum;
}


/**
 * @export
 */
export const EngineDeploymentDTOTypeEnum = {
    PUBLIC: 'PUBLIC',
    ON_PREMISE: 'ON_PREMISE',
    ON_PREMISE_MANAGED: 'ON_PREMISE_MANAGED',
    FULLY_MANAGED: 'FULLY_MANAGED'
} as const;
export type EngineDeploymentDTOTypeEnum = typeof EngineDeploymentDTOTypeEnum[keyof typeof EngineDeploymentDTOTypeEnum];

/**
 * @export
 */
export const EngineDeploymentDTOTierEnum = {
    SMALL: 'SMALL',
    MEDIUM: 'MEDIUM',
    LARGE: 'LARGE',
    EXTRA_LARGE: 'EXTRA_LARGE'
} as const;
export type EngineDeploymentDTOTierEnum = typeof EngineDeploymentDTOTierEnum[keyof typeof EngineDeploymentDTOTierEnum];


/**
 * Check if a given object implements the EngineDeploymentDTO interface.
 */
export function instanceOfEngineDeploymentDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function EngineDeploymentDTOFromJSON(json: any): EngineDeploymentDTO {
    return EngineDeploymentDTOFromJSONTyped(json, false);
}

export function EngineDeploymentDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EngineDeploymentDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'tier': !exists(json, 'tier') ? undefined : json['tier'],
    };
}

export function EngineDeploymentDTOToJSON(value?: EngineDeploymentDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'tier': value.tier,
    };
}

