/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ConditionalPathAction } from './ConditionalPathAction';
import {
    ConditionalPathActionFromJSON,
    ConditionalPathActionFromJSONTyped,
    ConditionalPathActionToJSON,
} from './ConditionalPathAction';

/**
 * 
 * @export
 * @interface FilterAction
 */
export interface FilterAction {
    /**
     * 
     * @type {string}
     * @memberof FilterAction
     */
    itemsToFilter: string;
    /**
     * 
     * @type {ConditionalPathAction}
     * @memberof FilterAction
     */
    condition: ConditionalPathAction;
}

/**
 * Check if a given object implements the FilterAction interface.
 */
export function instanceOfFilterAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "itemsToFilter" in value;
    isInstance = isInstance && "condition" in value;

    return isInstance;
}

export function FilterActionFromJSON(json: any): FilterAction {
    return FilterActionFromJSONTyped(json, false);
}

export function FilterActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'itemsToFilter': json['itemsToFilter'],
        'condition': ConditionalPathActionFromJSON(json['condition']),
    };
}

export function FilterActionToJSON(value?: FilterAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'itemsToFilter': value.itemsToFilter,
        'condition': ConditionalPathActionToJSON(value.condition),
    };
}

