/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Output } from './Output';
import {
    OutputFromJSON,
    OutputFromJSONTyped,
    OutputToJSON,
} from './Output';

/**
 * 
 * @export
 * @interface FindAndTransformAction
 */
export interface FindAndTransformAction {
    /**
     * 
     * @type {string}
     * @memberof FindAndTransformAction
     */
    input: string;
    /**
     * 
     * @type {Output}
     * @memberof FindAndTransformAction
     */
    response?: Output;
}

/**
 * Check if a given object implements the FindAndTransformAction interface.
 */
export function instanceOfFindAndTransformAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "input" in value;

    return isInstance;
}

export function FindAndTransformActionFromJSON(json: any): FindAndTransformAction {
    return FindAndTransformActionFromJSONTyped(json, false);
}

export function FindAndTransformActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindAndTransformAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'input': json['input'],
        'response': !exists(json, 'response') ? undefined : OutputFromJSON(json['response']),
    };
}

export function FindAndTransformActionToJSON(value?: FindAndTransformAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'input': value.input,
        'response': OutputToJSON(value.response),
    };
}

