/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GlobalVariableDTO
 */
export interface GlobalVariableDTO {
    /**
     * 
     * @type {string}
     * @memberof GlobalVariableDTO
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof GlobalVariableDTO
     */
    value?: string;
}

/**
 * Check if a given object implements the GlobalVariableDTO interface.
 */
export function instanceOfGlobalVariableDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function GlobalVariableDTOFromJSON(json: any): GlobalVariableDTO {
    return GlobalVariableDTOFromJSONTyped(json, false);
}

export function GlobalVariableDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalVariableDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function GlobalVariableDTOToJSON(value?: GlobalVariableDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'value': value.value,
    };
}

