/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstanceActionUpdateWebsocketDTO
 */
export interface InstanceActionUpdateWebsocketDTO {
    /**
     * 
     * @type {string}
     * @memberof InstanceActionUpdateWebsocketDTO
     */
    instanceId: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceActionUpdateWebsocketDTO
     */
    actionId: string;
    /**
     * 
     * @type {object}
     * @memberof InstanceActionUpdateWebsocketDTO
     */
    outputValues?: object;
    /**
     * 
     * @type {string}
     * @memberof InstanceActionUpdateWebsocketDTO
     */
    status?: InstanceActionUpdateWebsocketDTOStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof InstanceActionUpdateWebsocketDTO
     */
    executionTime?: number;
}


/**
 * @export
 */
export const InstanceActionUpdateWebsocketDTOStatusEnum = {
    READY: 'READY',
    RUNNING: 'RUNNING',
    ERROR: 'ERROR',
    FINISHED: 'FINISHED',
    OUT_OF_QUOTA: 'OUT_OF_QUOTA'
} as const;
export type InstanceActionUpdateWebsocketDTOStatusEnum = typeof InstanceActionUpdateWebsocketDTOStatusEnum[keyof typeof InstanceActionUpdateWebsocketDTOStatusEnum];


/**
 * Check if a given object implements the InstanceActionUpdateWebsocketDTO interface.
 */
export function instanceOfInstanceActionUpdateWebsocketDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "instanceId" in value;
    isInstance = isInstance && "actionId" in value;

    return isInstance;
}

export function InstanceActionUpdateWebsocketDTOFromJSON(json: any): InstanceActionUpdateWebsocketDTO {
    return InstanceActionUpdateWebsocketDTOFromJSONTyped(json, false);
}

export function InstanceActionUpdateWebsocketDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceActionUpdateWebsocketDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'instanceId': json['instanceId'],
        'actionId': json['actionId'],
        'outputValues': !exists(json, 'outputValues') ? undefined : json['outputValues'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'executionTime': !exists(json, 'executionTime') ? undefined : json['executionTime'],
    };
}

export function InstanceActionUpdateWebsocketDTOToJSON(value?: InstanceActionUpdateWebsocketDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'instanceId': value.instanceId,
        'actionId': value.actionId,
        'outputValues': value.outputValues,
        'status': value.status,
        'executionTime': value.executionTime,
    };
}

