/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GlobalVariableDTO } from './GlobalVariableDTO';
import {
    GlobalVariableDTOFromJSON,
    GlobalVariableDTOFromJSONTyped,
    GlobalVariableDTOToJSON,
} from './GlobalVariableDTO';

/**
 * 
 * @export
 * @interface InstanceUpdateWebsocketDTO
 */
export interface InstanceUpdateWebsocketDTO {
    /**
     * 
     * @type {string}
     * @memberof InstanceUpdateWebsocketDTO
     */
    instanceId: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceUpdateWebsocketDTO
     */
    status?: InstanceUpdateWebsocketDTOStatusEnum;
    /**
     * 
     * @type {{ [key: string]: object | undefined; }}
     * @memberof InstanceUpdateWebsocketDTO
     */
    tempVariables?: { [key: string]: object | undefined; };
    /**
     * 
     * @type {number}
     * @memberof InstanceUpdateWebsocketDTO
     */
    executionTime?: number;
    /**
     * 
     * @type {{ [key: string]: GlobalVariableDTO | undefined; }}
     * @memberof InstanceUpdateWebsocketDTO
     */
    globalVariables?: { [key: string]: GlobalVariableDTO | undefined; };
}


/**
 * @export
 */
export const InstanceUpdateWebsocketDTOStatusEnum = {
    READY: 'READY',
    RUNNING: 'RUNNING',
    ERROR: 'ERROR',
    FINISHED: 'FINISHED',
    OUT_OF_QUOTA: 'OUT_OF_QUOTA'
} as const;
export type InstanceUpdateWebsocketDTOStatusEnum = typeof InstanceUpdateWebsocketDTOStatusEnum[keyof typeof InstanceUpdateWebsocketDTOStatusEnum];


/**
 * Check if a given object implements the InstanceUpdateWebsocketDTO interface.
 */
export function instanceOfInstanceUpdateWebsocketDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "instanceId" in value;

    return isInstance;
}

export function InstanceUpdateWebsocketDTOFromJSON(json: any): InstanceUpdateWebsocketDTO {
    return InstanceUpdateWebsocketDTOFromJSONTyped(json, false);
}

export function InstanceUpdateWebsocketDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceUpdateWebsocketDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'instanceId': json['instanceId'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'tempVariables': !exists(json, 'tempVariables') ? undefined : json['tempVariables'],
        'executionTime': !exists(json, 'executionTime') ? undefined : json['executionTime'],
        'globalVariables': !exists(json, 'globalVariables') ? undefined : (mapValues(json['globalVariables'], GlobalVariableDTOFromJSON)),
    };
}

export function InstanceUpdateWebsocketDTOToJSON(value?: InstanceUpdateWebsocketDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'instanceId': value.instanceId,
        'status': value.status,
        'tempVariables': value.tempVariables,
        'executionTime': value.executionTime,
        'globalVariables': value.globalVariables === undefined ? undefined : (mapValues(value.globalVariables, GlobalVariableDTOToJSON)),
    };
}

