/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TelegramIntegrationWebhook } from './TelegramIntegrationWebhook';
import {
    TelegramIntegrationWebhookFromJSON,
    TelegramIntegrationWebhookFromJSONTyped,
    TelegramIntegrationWebhookToJSON,
} from './TelegramIntegrationWebhook';

/**
 * 
 * @export
 * @interface IntegrationWebhooks
 */
export interface IntegrationWebhooks {
    /**
     * 
     * @type {TelegramIntegrationWebhook}
     * @memberof IntegrationWebhooks
     */
    telegram?: TelegramIntegrationWebhook;
}

/**
 * Check if a given object implements the IntegrationWebhooks interface.
 */
export function instanceOfIntegrationWebhooks(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IntegrationWebhooksFromJSON(json: any): IntegrationWebhooks {
    return IntegrationWebhooksFromJSONTyped(json, false);
}

export function IntegrationWebhooksFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationWebhooks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'telegram': !exists(json, 'telegram') ? undefined : TelegramIntegrationWebhookFromJSON(json['telegram']),
    };
}

export function IntegrationWebhooksToJSON(value?: IntegrationWebhooks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'telegram': TelegramIntegrationWebhookToJSON(value.telegram),
    };
}

