/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthenticationMethods } from './AuthenticationMethods';
import {
    AuthenticationMethodsFromJSON,
    AuthenticationMethodsFromJSONTyped,
    AuthenticationMethodsToJSON,
} from './AuthenticationMethods';

/**
 * 
 * @export
 * @interface IntegrationMailConfig
 */
export interface IntegrationMailConfig {
    /**
     * 
     * @type {string}
     * @memberof IntegrationMailConfig
     */
    host: string;
    /**
     * 
     * @type {number}
     * @memberof IntegrationMailConfig
     */
    port: number;
    /**
     * 
     * @type {boolean}
     * @memberof IntegrationMailConfig
     */
    secure?: boolean;
    /**
     * 
     * @type {AuthenticationMethods}
     * @memberof IntegrationMailConfig
     */
    defaultAuthentication: AuthenticationMethods;
}

/**
 * Check if a given object implements the IntegrationMailConfig interface.
 */
export function instanceOfIntegrationMailConfig(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "host" in value;
    isInstance = isInstance && "port" in value;
    isInstance = isInstance && "defaultAuthentication" in value;

    return isInstance;
}

export function IntegrationMailConfigFromJSON(json: any): IntegrationMailConfig {
    return IntegrationMailConfigFromJSONTyped(json, false);
}

export function IntegrationMailConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationMailConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'host': json['host'],
        'port': json['port'],
        'secure': !exists(json, 'secure') ? undefined : json['secure'],
        'defaultAuthentication': AuthenticationMethodsFromJSON(json['defaultAuthentication']),
    };
}

export function IntegrationMailConfigToJSON(value?: IntegrationMailConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'host': value.host,
        'port': value.port,
        'secure': value.secure,
        'defaultAuthentication': AuthenticationMethodsToJSON(value.defaultAuthentication),
    };
}

