/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KeyValueStringPair
 */
export interface KeyValueStringPair {
    /**
     * 
     * @type {string}
     * @memberof KeyValueStringPair
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof KeyValueStringPair
     */
    value?: string;
}

/**
 * Check if a given object implements the KeyValueStringPair interface.
 */
export function instanceOfKeyValueStringPair(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function KeyValueStringPairFromJSON(json: any): KeyValueStringPair {
    return KeyValueStringPairFromJSONTyped(json, false);
}

export function KeyValueStringPairFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyValueStringPair {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function KeyValueStringPairToJSON(value?: KeyValueStringPair | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'value': value.value,
    };
}

