/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MailConfigurationOptions } from './MailConfigurationOptions';
import {
    MailConfigurationOptionsFromJSON,
    MailConfigurationOptionsFromJSONTyped,
    MailConfigurationOptionsToJSON,
} from './MailConfigurationOptions';

/**
 * 
 * @export
 * @interface MailAction
 */
export interface MailAction {
    /**
     * 
     * @type {MailConfigurationOptions}
     * @memberof MailAction
     */
    mailOption?: MailConfigurationOptions;
}

/**
 * Check if a given object implements the MailAction interface.
 */
export function instanceOfMailAction(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MailActionFromJSON(json: any): MailAction {
    return MailActionFromJSONTyped(json, false);
}

export function MailActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mailOption': !exists(json, 'mailOption') ? undefined : MailConfigurationOptionsFromJSON(json['mailOption']),
    };
}

export function MailActionToJSON(value?: MailAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mailOption': MailConfigurationOptionsToJSON(value.mailOption),
    };
}

