/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChatCompletion } from './ChatCompletion';
import {
    ChatCompletionFromJSON,
    ChatCompletionFromJSONTyped,
    ChatCompletionToJSON,
} from './ChatCompletion';

/**
 * 
 * @export
 * @interface OpenAiAction
 */
export interface OpenAiAction {
    /**
     * 
     * @type {ChatCompletion}
     * @memberof OpenAiAction
     */
    chatCompletion: ChatCompletion;
}

/**
 * Check if a given object implements the OpenAiAction interface.
 */
export function instanceOfOpenAiAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "chatCompletion" in value;

    return isInstance;
}

export function OpenAiActionFromJSON(json: any): OpenAiAction {
    return OpenAiActionFromJSONTyped(json, false);
}

export function OpenAiActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenAiAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chatCompletion': ChatCompletionFromJSON(json['chatCompletion']),
    };
}

export function OpenAiActionToJSON(value?: OpenAiAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chatCompletion': ChatCompletionToJSON(value.chatCompletion),
    };
}

