/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Output
 */
export interface Output {
    /**
     * 
     * @type {string}
     * @memberof Output
     */
    transformedValue?: string;
    /**
     * 
     * @type {string}
     * @memberof Output
     */
    type?: string;
}

/**
 * Check if a given object implements the Output interface.
 */
export function instanceOfOutput(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OutputFromJSON(json: any): Output {
    return OutputFromJSONTyped(json, false);
}

export function OutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): Output {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transformedValue': !exists(json, 'transformedValue') ? undefined : json['transformedValue'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function OutputToJSON(value?: Output | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transformedValue': value.transformedValue,
        'type': value.type,
    };
}

