/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OutputParameter
 */
export interface OutputParameter {
    /**
     * 
     * @type {string}
     * @memberof OutputParameter
     */
    parameterName: string;
}

/**
 * Check if a given object implements the OutputParameter interface.
 */
export function instanceOfOutputParameter(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "parameterName" in value;

    return isInstance;
}

export function OutputParameterFromJSON(json: any): OutputParameter {
    return OutputParameterFromJSONTyped(json, false);
}

export function OutputParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputParameter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parameterName': json['parameterName'],
    };
}

export function OutputParameterToJSON(value?: OutputParameter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parameterName': value.parameterName,
    };
}

