/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InstanceBaseDTO } from './InstanceBaseDTO';
import {
    InstanceBaseDTOFromJSON,
    InstanceBaseDTOFromJSONTyped,
    InstanceBaseDTOToJSON,
} from './InstanceBaseDTO';

/**
 * 
 * @export
 * @interface PagingResponseDTOInstanceBaseDTO
 */
export interface PagingResponseDTOInstanceBaseDTO {
    /**
     * 
     * @type {Array<InstanceBaseDTO>}
     * @memberof PagingResponseDTOInstanceBaseDTO
     */
    response: Array<InstanceBaseDTO>;
    /**
     * 
     * @type {number}
     * @memberof PagingResponseDTOInstanceBaseDTO
     */
    total: number;
    /**
     * 
     * @type {boolean}
     * @memberof PagingResponseDTOInstanceBaseDTO
     */
    hasNext: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagingResponseDTOInstanceBaseDTO
     */
    hasPrevious: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagingResponseDTOInstanceBaseDTO
     */
    hasContent: boolean;
}

/**
 * Check if a given object implements the PagingResponseDTOInstanceBaseDTO interface.
 */
export function instanceOfPagingResponseDTOInstanceBaseDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "response" in value;
    isInstance = isInstance && "total" in value;
    isInstance = isInstance && "hasNext" in value;
    isInstance = isInstance && "hasPrevious" in value;
    isInstance = isInstance && "hasContent" in value;

    return isInstance;
}

export function PagingResponseDTOInstanceBaseDTOFromJSON(json: any): PagingResponseDTOInstanceBaseDTO {
    return PagingResponseDTOInstanceBaseDTOFromJSONTyped(json, false);
}

export function PagingResponseDTOInstanceBaseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagingResponseDTOInstanceBaseDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': ((json['response'] as Array<any>).map(InstanceBaseDTOFromJSON)),
        'total': json['total'],
        'hasNext': json['hasNext'],
        'hasPrevious': json['hasPrevious'],
        'hasContent': json['hasContent'],
    };
}

export function PagingResponseDTOInstanceBaseDTOToJSON(value?: PagingResponseDTOInstanceBaseDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ((value.response as Array<any>).map(InstanceBaseDTOToJSON)),
        'total': value.total,
        'hasNext': value.hasNext,
        'hasPrevious': value.hasPrevious,
        'hasContent': value.hasContent,
    };
}

