/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WorkflowModel } from './WorkflowModel';
import {
    WorkflowModelFromJSON,
    WorkflowModelFromJSONTyped,
    WorkflowModelToJSON,
} from './WorkflowModel';

/**
 * 
 * @export
 * @interface PagingResponseDTOWorkflowModel
 */
export interface PagingResponseDTOWorkflowModel {
    /**
     * 
     * @type {Array<WorkflowModel>}
     * @memberof PagingResponseDTOWorkflowModel
     */
    response: Array<WorkflowModel>;
    /**
     * 
     * @type {number}
     * @memberof PagingResponseDTOWorkflowModel
     */
    total: number;
    /**
     * 
     * @type {boolean}
     * @memberof PagingResponseDTOWorkflowModel
     */
    hasNext: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagingResponseDTOWorkflowModel
     */
    hasPrevious: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagingResponseDTOWorkflowModel
     */
    hasContent: boolean;
}

/**
 * Check if a given object implements the PagingResponseDTOWorkflowModel interface.
 */
export function instanceOfPagingResponseDTOWorkflowModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "response" in value;
    isInstance = isInstance && "total" in value;
    isInstance = isInstance && "hasNext" in value;
    isInstance = isInstance && "hasPrevious" in value;
    isInstance = isInstance && "hasContent" in value;

    return isInstance;
}

export function PagingResponseDTOWorkflowModelFromJSON(json: any): PagingResponseDTOWorkflowModel {
    return PagingResponseDTOWorkflowModelFromJSONTyped(json, false);
}

export function PagingResponseDTOWorkflowModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagingResponseDTOWorkflowModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': ((json['response'] as Array<any>).map(WorkflowModelFromJSON)),
        'total': json['total'],
        'hasNext': json['hasNext'],
        'hasPrevious': json['hasPrevious'],
        'hasContent': json['hasContent'],
    };
}

export function PagingResponseDTOWorkflowModelToJSON(value?: PagingResponseDTOWorkflowModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ((value.response as Array<any>).map(WorkflowModelToJSON)),
        'total': value.total,
        'hasNext': value.hasNext,
        'hasPrevious': value.hasPrevious,
        'hasContent': value.hasContent,
    };
}

