/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountMember } from './AccountMember';
import {
    AccountMemberFromJSON,
    AccountMemberFromJSONTyped,
    AccountMemberToJSON,
} from './AccountMember';

/**
 * 
 * @export
 * @interface PairAccountMemberString
 */
export interface PairAccountMemberString {
    /**
     * 
     * @type {AccountMember}
     * @memberof PairAccountMemberString
     */
    first: AccountMember;
    /**
     * 
     * @type {string}
     * @memberof PairAccountMemberString
     */
    second: string;
}

/**
 * Check if a given object implements the PairAccountMemberString interface.
 */
export function instanceOfPairAccountMemberString(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "first" in value;
    isInstance = isInstance && "second" in value;

    return isInstance;
}

export function PairAccountMemberStringFromJSON(json: any): PairAccountMemberString {
    return PairAccountMemberStringFromJSONTyped(json, false);
}

export function PairAccountMemberStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): PairAccountMemberString {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'first': AccountMemberFromJSON(json['first']),
        'second': json['second'],
    };
}

export function PairAccountMemberStringToJSON(value?: PairAccountMemberString | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'first': AccountMemberToJSON(value.first),
        'second': value.second,
    };
}

