/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParallelAction
 */
export interface ParallelAction {
    /**
     * 
     * @type {boolean}
     * @memberof ParallelAction
     */
    waitAll: boolean;
}

/**
 * Check if a given object implements the ParallelAction interface.
 */
export function instanceOfParallelAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "waitAll" in value;

    return isInstance;
}

export function ParallelActionFromJSON(json: any): ParallelAction {
    return ParallelActionFromJSONTyped(json, false);
}

export function ParallelActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParallelAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'waitAll': json['waitAll'],
    };
}

export function ParallelActionToJSON(value?: ParallelAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'waitAll': value.waitAll,
    };
}

