/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserQuota } from './UserQuota';
import {
    UserQuotaFromJSON,
    UserQuotaFromJSONTyped,
    UserQuotaToJSON,
} from './UserQuota';

/**
 * 
 * @export
 * @interface QuotaWorkspaceCurrentState
 */
export interface QuotaWorkspaceCurrentState {
    /**
     * 
     * @type {string}
     * @memberof QuotaWorkspaceCurrentState
     */
    accountId: string;
    /**
     * 
     * @type {{ [key: string]: number | undefined; }}
     * @memberof QuotaWorkspaceCurrentState
     */
    projectWorkflowsCount: { [key: string]: number | undefined; };
    /**
     * 
     * @type {UserQuota}
     * @memberof QuotaWorkspaceCurrentState
     */
    quota: UserQuota;
}

/**
 * Check if a given object implements the QuotaWorkspaceCurrentState interface.
 */
export function instanceOfQuotaWorkspaceCurrentState(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountId" in value;
    isInstance = isInstance && "projectWorkflowsCount" in value;
    isInstance = isInstance && "quota" in value;

    return isInstance;
}

export function QuotaWorkspaceCurrentStateFromJSON(json: any): QuotaWorkspaceCurrentState {
    return QuotaWorkspaceCurrentStateFromJSONTyped(json, false);
}

export function QuotaWorkspaceCurrentStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuotaWorkspaceCurrentState {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'projectWorkflowsCount': json['projectWorkflowsCount'],
        'quota': UserQuotaFromJSON(json['quota']),
    };
}

export function QuotaWorkspaceCurrentStateToJSON(value?: QuotaWorkspaceCurrentState | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountId': value.accountId,
        'projectWorkflowsCount': value.projectWorkflowsCount,
        'quota': UserQuotaToJSON(value.quota),
    };
}

