/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendMeInstanceDTO
 */
export interface SendMeInstanceDTO {
    /**
     * 
     * @type {string}
     * @memberof SendMeInstanceDTO
     */
    workflowId: string;
    /**
     * 
     * @type {string}
     * @memberof SendMeInstanceDTO
     */
    triggeredBy: SendMeInstanceDTOTriggeredByEnum;
}


/**
 * @export
 */
export const SendMeInstanceDTOTriggeredByEnum = {
    WEBHOOK: 'WEBHOOK',
    MANUAL: 'MANUAL',
    CRON_JOB: 'CRON_JOB'
} as const;
export type SendMeInstanceDTOTriggeredByEnum = typeof SendMeInstanceDTOTriggeredByEnum[keyof typeof SendMeInstanceDTOTriggeredByEnum];


/**
 * Check if a given object implements the SendMeInstanceDTO interface.
 */
export function instanceOfSendMeInstanceDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "workflowId" in value;
    isInstance = isInstance && "triggeredBy" in value;

    return isInstance;
}

export function SendMeInstanceDTOFromJSON(json: any): SendMeInstanceDTO {
    return SendMeInstanceDTOFromJSONTyped(json, false);
}

export function SendMeInstanceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMeInstanceDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'workflowId': json['workflowId'],
        'triggeredBy': json['triggeredBy'],
    };
}

export function SendMeInstanceDTOToJSON(value?: SendMeInstanceDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'workflowId': value.workflowId,
        'triggeredBy': value.triggeredBy,
    };
}

