/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValueGetterAction
 */
export interface ValueGetterAction {
    /**
     * 
     * @type {string}
     * @memberof ValueGetterAction
     */
    value?: string;
    /**
     * 
     * @type {string}
     * @memberof ValueGetterAction
     */
    path?: string;
}

/**
 * Check if a given object implements the ValueGetterAction interface.
 */
export function instanceOfValueGetterAction(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ValueGetterActionFromJSON(json: any): ValueGetterAction {
    return ValueGetterActionFromJSONTyped(json, false);
}

export function ValueGetterActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValueGetterAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function ValueGetterActionToJSON(value?: ValueGetterAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'path': value.path,
    };
}

