/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { KeyValueStringPair } from './KeyValueStringPair';
import {
    KeyValueStringPairFromJSON,
    KeyValueStringPairFromJSONTyped,
    KeyValueStringPairToJSON,
} from './KeyValueStringPair';

/**
 * 
 * @export
 * @interface WebhookResponse
 */
export interface WebhookResponse {
    /**
     * 
     * @type {number}
     * @memberof WebhookResponse
     */
    code?: number;
    /**
     * 
     * @type {Array<KeyValueStringPair>}
     * @memberof WebhookResponse
     */
    headers?: Array<KeyValueStringPair>;
    /**
     * 
     * @type {string}
     * @memberof WebhookResponse
     */
    data?: string;
}

/**
 * Check if a given object implements the WebhookResponse interface.
 */
export function instanceOfWebhookResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WebhookResponseFromJSON(json: any): WebhookResponse {
    return WebhookResponseFromJSONTyped(json, false);
}

export function WebhookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'headers': !exists(json, 'headers') ? undefined : ((json['headers'] as Array<any>).map(KeyValueStringPairFromJSON)),
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function WebhookResponseToJSON(value?: WebhookResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'headers': value.headers === undefined ? undefined : ((value.headers as Array<any>).map(KeyValueStringPairToJSON)),
        'data': value.data,
    };
}

