/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkflowEventAction
 */
export interface WorkflowEventAction {
    /**
     * 
     * @type {number}
     * @memberof WorkflowEventAction
     */
    time?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkflowEventAction
     */
    type: WorkflowEventActionTypeEnum;
}


/**
 * @export
 */
export const WorkflowEventActionTypeEnum = {
    END: 'END',
    ERROR: 'ERROR',
    CANCEL: 'CANCEL',
    WAIT_TIMER: 'WAIT_TIMER',
    WAIT_UNTIL: 'WAIT_UNTIL'
} as const;
export type WorkflowEventActionTypeEnum = typeof WorkflowEventActionTypeEnum[keyof typeof WorkflowEventActionTypeEnum];


/**
 * Check if a given object implements the WorkflowEventAction interface.
 */
export function instanceOfWorkflowEventAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function WorkflowEventActionFromJSON(json: any): WorkflowEventAction {
    return WorkflowEventActionFromJSONTyped(json, false);
}

export function WorkflowEventActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowEventAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'time': !exists(json, 'time') ? undefined : json['time'],
        'type': json['type'],
    };
}

export function WorkflowEventActionToJSON(value?: WorkflowEventAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'time': value.time,
        'type': value.type,
    };
}

