/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GlobalVariableDTO } from './GlobalVariableDTO';
import {
    GlobalVariableDTOFromJSON,
    GlobalVariableDTOFromJSONTyped,
    GlobalVariableDTOToJSON,
} from './GlobalVariableDTO';
import type { WorkflowTemplate } from './WorkflowTemplate';
import {
    WorkflowTemplateFromJSON,
    WorkflowTemplateFromJSONTyped,
    WorkflowTemplateToJSON,
} from './WorkflowTemplate';
import type { WorkflowTrigger } from './WorkflowTrigger';
import {
    WorkflowTriggerFromJSON,
    WorkflowTriggerFromJSONTyped,
    WorkflowTriggerToJSON,
} from './WorkflowTrigger';

/**
 * 
 * @export
 * @interface WorkflowModel
 */
export interface WorkflowModel {
    /**
     * 
     * @type {string}
     * @memberof WorkflowModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowModel
     */
    workspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowModel
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowModel
     */
    status: WorkflowModelStatusEnum;
    /**
     * 
     * @type {WorkflowTrigger}
     * @memberof WorkflowModel
     */
    trigger: WorkflowTrigger;
    /**
     * 
     * @type {string}
     * @memberof WorkflowModel
     */
    region: string;
    /**
     * 
     * @type {Array<GlobalVariableDTO>}
     * @memberof WorkflowModel
     */
    globalVariables: Array<GlobalVariableDTO>;
    /**
     * 
     * @type {string}
     * @memberof WorkflowModel
     */
    copyOfWorkflowId?: string;
    /**
     * 
     * @type {WorkflowTemplate}
     * @memberof WorkflowModel
     */
    template?: WorkflowTemplate;
    /**
     * 
     * @type {number}
     * @memberof WorkflowModel
     */
    rotationPeriod: number;
    /**
     * 
     * @type {number}
     * @memberof WorkflowModel
     */
    version?: number;
    /**
     * 
     * @type {Date}
     * @memberof WorkflowModel
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof WorkflowModel
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof WorkflowModel
     */
    userName?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowModel
     */
    userId?: string;
}


/**
 * @export
 */
export const WorkflowModelStatusEnum = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE'
} as const;
export type WorkflowModelStatusEnum = typeof WorkflowModelStatusEnum[keyof typeof WorkflowModelStatusEnum];


/**
 * Check if a given object implements the WorkflowModel interface.
 */
export function instanceOfWorkflowModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "workspaceId" in value;
    isInstance = isInstance && "projectId" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "trigger" in value;
    isInstance = isInstance && "region" in value;
    isInstance = isInstance && "globalVariables" in value;
    isInstance = isInstance && "rotationPeriod" in value;

    return isInstance;
}

export function WorkflowModelFromJSON(json: any): WorkflowModel {
    return WorkflowModelFromJSONTyped(json, false);
}

export function WorkflowModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'workspaceId': json['workspaceId'],
        'projectId': json['projectId'],
        'name': json['name'],
        'status': json['status'],
        'trigger': WorkflowTriggerFromJSON(json['trigger']),
        'region': json['region'],
        'globalVariables': ((json['globalVariables'] as Array<any>).map(GlobalVariableDTOFromJSON)),
        'copyOfWorkflowId': !exists(json, 'copyOfWorkflowId') ? undefined : json['copyOfWorkflowId'],
        'template': !exists(json, 'template') ? undefined : WorkflowTemplateFromJSON(json['template']),
        'rotationPeriod': json['rotationPeriod'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'userName': !exists(json, 'userName') ? undefined : json['userName'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function WorkflowModelToJSON(value?: WorkflowModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'workspaceId': value.workspaceId,
        'projectId': value.projectId,
        'name': value.name,
        'status': value.status,
        'trigger': WorkflowTriggerToJSON(value.trigger),
        'region': value.region,
        'globalVariables': ((value.globalVariables as Array<any>).map(GlobalVariableDTOToJSON)),
        'copyOfWorkflowId': value.copyOfWorkflowId,
        'template': WorkflowTemplateToJSON(value.template),
        'rotationPeriod': value.rotationPeriod,
        'version': value.version,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'userName': value.userName,
        'userId': value.userId,
    };
}

