/* tslint:disable */
/* eslint-disable */
/**
 * Bigration API
 * Bigration
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CalculatedAccountStatisticModel,
} from '../models';
import {
    CalculatedAccountStatisticModelFromJSON,
    CalculatedAccountStatisticModelToJSON,
} from '../models';

export interface AccountStatisticByIdForWorkflowServiceClientRequest {
    calculatedAccountStatisticId: string;
}

/**
 * WorkflowEngineServiceApiInstanceControllerApi - interface
 * 
 * @export
 * @interface WorkflowEngineServiceApiInstanceControllerApiInterface
 */
export interface WorkflowEngineServiceApiInstanceControllerApiInterface {
    /**
     * 
     * @param {string} calculatedAccountStatisticId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowEngineServiceApiInstanceControllerApiInterface
     */
    accountStatisticByIdForWorkflowServiceClientRaw(requestParameters: AccountStatisticByIdForWorkflowServiceClientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CalculatedAccountStatisticModel>>;

    /**
     */
    accountStatisticByIdForWorkflowServiceClient(requestParameters: AccountStatisticByIdForWorkflowServiceClientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CalculatedAccountStatisticModel>;

}

/**
 * 
 */
export class WorkflowEngineServiceApiInstanceControllerApi extends runtime.BaseAPI implements WorkflowEngineServiceApiInstanceControllerApiInterface {

    /**
     */
    async accountStatisticByIdForWorkflowServiceClientRaw(requestParameters: AccountStatisticByIdForWorkflowServiceClientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CalculatedAccountStatisticModel>> {
        if (requestParameters.calculatedAccountStatisticId === null || requestParameters.calculatedAccountStatisticId === undefined) {
            throw new runtime.RequiredError('calculatedAccountStatisticId','Required parameter requestParameters.calculatedAccountStatisticId was null or undefined when calling accountStatisticByIdForWorkflowServiceClient.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/service-api/instance/statistic/{calculatedAccountStatisticId}`.replace(`{${"calculatedAccountStatisticId"}}`, encodeURIComponent(String(requestParameters.calculatedAccountStatisticId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CalculatedAccountStatisticModelFromJSON(jsonValue));
    }

    /**
     */
    async accountStatisticByIdForWorkflowServiceClient(requestParameters: AccountStatisticByIdForWorkflowServiceClientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CalculatedAccountStatisticModel> {
        const response = await this.accountStatisticByIdForWorkflowServiceClientRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
